// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWqunU9DJ9EaBxPwMVrfM_bOh16kEMmFQ',
    appId: '1:813109637442:web:f3263d628ee751b93d58db',
    messagingSenderId: '813109637442',
    projectId: 'vtha-229de',
    authDomain: 'vtha-229de.firebaseapp.com',
    storageBucket: 'vtha-229de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfjhsg004Y2Nwy4bS3L8o4xn2ebbTv-V0',
    appId: '1:813109637442:android:73bd1fdc2155b11f3d58db',
    messagingSenderId: '813109637442',
    projectId: 'vtha-229de',
    storageBucket: 'vtha-229de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZB41WXFRD7ycnQIP0FeU2zMpVb4H6zLo',
    appId: '1:813109637442:ios:c4686f440db42bf73d58db',
    messagingSenderId: '813109637442',
    projectId: 'vtha-229de',
    storageBucket: 'vtha-229de.appspot.com',
    iosBundleId: 'com.example.vthaxfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZB41WXFRD7ycnQIP0FeU2zMpVb4H6zLo',
    appId: '1:813109637442:ios:c4686f440db42bf73d58db',
    messagingSenderId: '813109637442',
    projectId: 'vtha-229de',
    storageBucket: 'vtha-229de.appspot.com',
    iosBundleId: 'com.example.vthaxfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWqunU9DJ9EaBxPwMVrfM_bOh16kEMmFQ',
    appId: '1:813109637442:web:ee0d6f2121c634793d58db',
    messagingSenderId: '813109637442',
    projectId: 'vtha-229de',
    authDomain: 'vtha-229de.firebaseapp.com',
    storageBucket: 'vtha-229de.appspot.com',
  );
}